name: Python Package using Conda (Windows)

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        auto-activate-base: false
        python-version: '3.12'
    - name: Check if environment.yml exists
      run: |
        if not exist environment.yml exit 1
    - name: Create and activate environment
      run: |
        conda create --name myenv python=3.12 -y
        echo "conda activate myenv" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        conda install --name myenv --file environment.yml -y
    - name: Lint with flake8
      run: |
        conda run --name myenv flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run --name myenv flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda run --name myenv pytest
